POST  http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "fundsff",
    "email": "tattuong2812",
    "password": "fun"
}


###

POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "funn",
    "password": "fun"
}


###
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGZjZTkyZGY0NTIyMDc3MzhkNGZjNzMiLCJpYXQiOjE2MjcxODc1MDF9.wuLLKh96MG-lrH7RkUCdhMRtEk4q1EcHxnv7fQ5MBio

{
    "title": "ddsdsd",
    "description": "aafffaa",
    "status": "TO LEARN",
    "url": "google.cdfdfom"    
}